from . import base

class ConnectionError(base.BaseException): pass
